client.auto_restart=true
client.network_timeout=1200
client.user_agent=Railway-SheepIt-Client/1.0
client.max_cores=24
client.max_memory=24000
client.server=https://client.sheepit-renderfarm.com
client.keepalive_interval=60
client.cache_dir=/cache
client.log_file=disabled